name: admin_voting
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  packages: 
    git: https://github.com/rahmat999ht/packages.git
  cloud_firestore: ^4.8.4
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.0
  line_icons: ^2.0.3
  google_nav_bar: ^5.0.6

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

